### ISSUE TITLE
Cannot update multitenancy postgresql_connection_uri from api

### ISSUE THREAD

**Issue by fedeGiudici** [supertokens/supertokens-postgresql-plugin#190] opened 2024-02-13 14:37 UTC
Hope this is the right place, otherwise tell me where to put it.

Currently we are trying the multitenancy in our dev environment. we prepared a docker-compose.yml with 2 database to have data segregation.

```
services:
  supertokens-core:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:7.0
    ports:
      - "3567:3567"
#    environment:
#      POSTGRESQL_CONNECTION_URI: "postgresql://supertokens:supertokens@supertokens-db:5432/supertokens"
    depends_on: 
      - supertokens-db-1
      - supertokens-db-2
  
  supertokens-db-1:
    image: postgres:11.13
    restart: always
    environment:
      POSTGRES_DB: supertokens
      POSTGRES_USER: supertokens
      POSTGRES_PASSWORD: supertokens
    ports:
      - '45432:5432'
    volumes:
      - .data/supertokens-db-1:/var/lib/postgresql/data

  supertokens-db-2:
    image: postgres:11.13
    restart: always
    environment:
      POSTGRES_DB: supertokens
      POSTGRES_USER: supertokens
      POSTGRES_PASSWORD: supertokens
    ports:
      - '45433:5432'
    volumes:
      - .data/supertokens-db-2:/var/lib/postgresql/data

```

We are following the guide [https://supertokens.com/docs/multitenancy/new-tenant](https://supertokens.com/docs/multitenancy/new-tenant) but when we try to perform the update call to change the postgresql_connection_uri an error occurs and we cannot use the second db for the second tenant.

```
curl --location --request PUT 'http://localhost:3567/recipe/multitenancy/tenant' \
--header 'Content-Type: application/json' \
--data-raw '{
    "tenantId": "TENANT2",
    "coreConfig": {
        "email_verification_token_lifetime": 7200000,
        "password_reset_token_lifetime": 3600000,
       "postgresql_connection_uri": "postgresql://localhost:45433/supertokens"
    }   
}'
```

**Comment by rishabhpoddar** [comment] 2024-02-15 07:52
Hi. The issue is that the core is running with an in memory database since you have not provided it a postgresql_connection_uri on startup (it's commented in the docker compose file). You need to give it one db so it can initialise itself, and then when you create a tenant, by default, it will connect to that database, unless you specify a `postgresql_connection_uri` for that tenant.

**Comment by rishabhpoddar** [comment] 2024-02-15 09:58
Closing this issue since it doesn't seem to be a bug in supertokens. But feel free to reopen it.

**Closed by rishabhpoddar** 2024-02-15 09:58 UTC
